# Generated by Django 3.2.4 on 2021-06-20 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jaguareteKaa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='user',
            field=models.CharField(default='USER001', max_length=64),
        ),
        migrations.AlterField(
            model_name='producto',
            name='description',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='producto',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
