# Generated by Django 3.2.4 on 2021-06-20 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jaguareteKaa', '0004_auto_20210620_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(default='All', max_length=150),
        ),
        migrations.AlterField(
            model_name='producto',
            name='image',
            field=models.ImageField(upload_to='servicios'),
        ),
    ]
