# Generated by Django 3.2.4 on 2021-06-20 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jaguareteKaa', '0005_auto_20210620_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='image',
            field=models.ImageField(upload_to='productos'),
        ),
    ]
