# Generated by Django 3.2.4 on 2021-06-21 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jaguareteKaa', '0008_auto_20210620_0517'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.BooleanField(default=True),
        ),
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='jaguareteKaa.categoria'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.FloatField(default=0),
        ),
    ]
